{{- $registry := .Values.runtime.image.registry | default .Values.global.image.registry | default "docker.io" -}}
{{- $top := . }}
{{- range .Values.runtime.hostGroups }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hostgroup-{{ .name }}
  namespace: {{ $top.Release.Namespace }}
  labels:
    wasmcloud.com/name: hostgroup
    wasmcloud.com/hostgroup: {{ .name }}
    {{- include "runtime-operator.labels" $top | nindent 4 }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      wasmcloud.com/name: hostgroup
      wasmcloud.com/hostgroup: {{ .name }}
  template:
    metadata:
      labels:
        wasmcloud.com/name: hostgroup
        wasmcloud.com/hostgroup: {{ .name }}
        {{- include "runtime-operator.labels" $top | nindent 8 }}
    spec:
      serviceAccountName: {{ include "runtime-operator.serviceAccountName" $top }}-runtime
      {{- include "runtime-operator.imagePullSecrets" $top | nindent 6 }}
      containers:
        - name: host
          image: {{ printf "%s/%s" $registry $top.Values.runtime.image.repository }}:{{ $top.Values.runtime.image.tag | default $top.Chart.AppVersion }}
          env:
            - name: WASMCLOUD_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - "host"
            - "--host-name=$(WASMCLOUD_HOST_IP)"
            - "--host-group={{ .name }}"
            - "--scheduler-nats-url={{ $top.Values.runtime.nats.schedulerUrl }}"
            - "--data-nats-url={{ $top.Values.runtime.nats.dataUrl }}"
            {{- if $top.Values.runtime.nats.tls.ca }}
            - "--nats-tls-ca={{ $top.Values.runtime.nats.tls.ca }}"
            {{- end }}
            {{- if $top.Values.runtime.nats.tls.handshakeFirst }}
            - "--nats-tls-first"
            {{- end }}
            {{- if $top.Values.runtime.nats.credentials }}
            - "--nats-creds={{ $top.Values.runtime.nats.credentials }}"
            {{- end }}
            {{- if and (.http) (.http.enabled) }}
            - "--http-addr=0.0.0.0:9191"
            {{- end }}
            {{- if and (.webgpu) (.webgpu.enabled) }}
            - "--wasi-webgpu"
            {{- end }}
            {{- if and (.surrealdb) (.surrealdb.enabled) }}
            - "--surrealdb-url={{ .surrealdb.url }}"
            - "--surrealdb-namespace={{ .surrealdb.namespace | default "test" }}"
            - "--surrealdb-database={{ .surrealdb.database | default "test" }}"
            - "--surrealdb-auth={{ .surrealdb.auth | default "root" }}"
            {{- end }}
          imagePullPolicy: {{ $top.Values.runtime.image.pull_policy }}
          {{- if or ($top.Values.runtime.extraEnv) (.extraEnv) (and (.surrealdb) (.surrealdb.enabled)) }}
          env:
            {{- if and (.surrealdb) (.surrealdb.enabled) }}
            {{- if .surrealdb.existingSecret }}
            - name: SURREALDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .surrealdb.existingSecret }}
                  key: username
            - name: SURREALDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .surrealdb.existingSecret }}
                  key: password
            {{- else }}
            {{- if .surrealdb.username }}
            - name: SURREALDB_USERNAME
              value: {{ .surrealdb.username | quote }}
            {{- end }}
            {{- if .surrealdb.password }}
            - name: SURREALDB_PASSWORD
              value: {{ .surrealdb.password | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
            {{- with $top.Values.runtime.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- with .extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- end }}
          {{- with .resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            {{- if and (.http) (.http.enabled) }}
            - name: http
              containerPort: 9191
              protocol: TCP
            {{- end }}
          {{- with $top.Values.runtime.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            capabilities:
              drop:
                - NET_RAW
      {{- with $top.Values.runtime.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0
---
{{- end }}