{{- $registry := .Values.operator.image.registry | default .Values.global.image.registry | default "docker.io" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: runtime-operator
  namespace: {{ .Release.Namespace }}
  labels:
    wasmcloud.com/name: runtime-operator
    {{- include "runtime-operator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      wasmcloud.com/name: runtime-operator
  template:
    metadata:
      labels:
        wasmcloud.com/name: runtime-operator
        {{- include "runtime-operator.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "runtime-operator.serviceAccountName" . }}
      {{- include "runtime-operator.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: runtime-operator
          image: {{ printf "%s/%s" $registry .Values.operator.image.repository }}:{{ .Values.operator.image.tag | default .Chart.AppVersion }}
          args:
            - "-nats-url={{ .Values.operator.nats.url }}"
            {{- if .Values.operator.nats.tls.ca }}
            - "-nats-tls-ca={{ .Values.operator.nats.tls.ca }}"
            {{- end }}
            {{- if .Values.operator.nats.tls.handshakeFirst }}
            - "-nats-tls-first"
            {{- end }}
            {{- if .Values.operator.nats.credentials }}
            - "-nats-creds={{ .Values.operator.nats.credentials }}"
            {{- end }}
          imagePullPolicy: {{ .Values.operator.image.pull_policy }}
          {{- with .Values.operator.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            capabilities:
              drop:
                - NET_RAW
      {{- with .Values.operator.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 0